version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish -c Release
      - zip package.zip CRMApi/bin/Release/netcoreapp2.0/publish/*
artifacts:
  files:
    - package.zip
    - serverless.yaml