version: 0.3

phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish -c Release
      - (cd CRMApi && dotnet lambda deploy-serverless --config-file ../aws-lambda-tools-defaults.json)
